VULN-419 upgrade package python from 3.11 to 3.12
monte-carlo-data/apollo-agent pull request #140
Opened 2024-10-03 23:58 UTC by romanoff

Updated python version and setuptools version to eliminate vulnurabilities

Context:
https://linear.app/montecarlodata/issue/VULN-419/upgrade-package-python-high
https://linear.app/montecarlodata/issue/VULN-423/major-upgrade-for-setuptools-high

2024-10-04 00:30 UTC, lexicalunit commented
When updating the python version we probably also have to update the `psycopg2-binary` version too.

2024-10-04 16:23 UTC, lexicalunit commented on tests/test_azure_blob_storage_proxy.py
> +        mock_temp_file_path.assert_called_once()
Nice! It was python 3.12 that flagged these I bet 🤘

2024-10-04 16:25 UTC, lexicalunit approved these changes
I recently added some documentation on how to bake apollo changes on `dev` before merging them into production: https://www.notion.so/montecarlodata/Agents-working-on-vulnerability-issues-e240ca5352b04754a1cfbc1632294b28?pvs=4#8a288a33bb3e416ab76913bfb35b8142

Lemme know if it helps or if you'd add anything else to it!

2024-10-04 22:23 UTC, romanoff commented on Dockerfile
> +    && apt-get install -y msodbcsql17 odbcinst odbcinst1debian2 unixodbc-dev unixodbc
I checked and it installs `2.3.11-3` of odbcinst, odbcinst1debian2, unixodbc-dev, unixodbc in this case. Using `mcr.microsoft.com/azure-functions/python:4-python3.12` `2.3.11-1` option was not available. Should that be fine? @mrostan

2024-10-04 23:04 UTC, lexicalunit commented on Dockerfile
> +    && apt-get install -y msodbcsql17 odbcinst odbcinst1debian2 unixodbc-dev unixodbc
There's a nifty Dockerfile linter that checks for best practice adherence I use called `hadolint`. One thing I recommends is that we pin version for `apt-get install` commands: https://github.com/hadolint/hadolint/wiki/DL3008

This is also recommended by Docker in their [Best practices documentation](https://docs.docker.com/build/building/best-practices/):

> Version pinning forces the build to retrieve a particular version regardless of what’s in the cache. This technique can also reduce failures due to unanticipated changes in required packages.

I think `2.3.11-3` is ok, but I would keep pinning, and just update the version to match what gets installed here.

2024-10-04 23:06 UTC, lexicalunit commented on Dockerfile
> +    && apt-get install -y msodbcsql17 odbcinst odbcinst1debian2 unixodbc-dev unixodbc
Also I think we should keep the `ACCEPT_EULA=Y` part as it's recommended by Microsoft: https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Cdebian17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline

2024-10-04 23:08 UTC, lexicalunit requested changes
Nit: We should update version pinnings and keep them.

Issue: We should keep the `ACCEPT_EULA=Y` in accordance with MS installation guide.

2024-10-16 19:16 UTC, lexicalunit approved these changes

2024-10-16 19:17 UTC, mrostan approved these changes
lgtm

2024-10-16 21:01 UTC, merged